- name: Create Compute Engine instances
  hosts: localhost
  gather_facts: no
  tasks:
   - name: Create private IP address to the VM instance
     gcp_compute_address:
       name: "{{ gcp_zone }}-ip"
       region: "{{ gcp_region }}"
       project: "{{ gcp_project }}"
       service_account_file: "{{ gcp_cred_file }}"
       auth_kind: "{{ gcp_cred_kind }}"
     register: gce_ip
   - name: Bring up the instance in the gcp_zone
     gcp_compute_instance:
       name: "{{ gcp_zone }}"
       machine_type: "{{ gcp_machine_type }}"
       disks:
         - auto_delete: true
           boot: true
           initialize_params:
             source_image: "{{ gcp_image_type }}"
       network_interfaces:
         - access_configs:
             - name: External NAT  # public IP
               nat_ip: "{{ gce_ip }}"
               type: ONE_TO_ONE_NAT
       gcp_zone: "{{ gcp_zone }}"
       project: "{{ gcp_project }}"
       service_account_file: "{{ gcp_cred_file }}"
       auth_kind: "{{ gcp_cred_kind }}"
     register: gce 