# Playbook to deploy Ghost and its components

- name: Create namespace
  hosts: localhost
  gather_facts: false
  roles:
      - k8/namespace

- name: Create SQL database
  hosts: localhost
  gather_facts: false
  roles:
    - ghost_db

- name: Deploy Ghost Application
  hosts: localhost
  gather_facts: false
  roles:
      - ghost_app/deploy-ghost


