#https://ghost.org/docs/ghost-cli/
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  namespace: ascn-cluster
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:5.14.1
        env: # The variables below could be set on a ConfigMap object
        - name: database__connection__database 
          value: ghost
        - name: database__connection__user
          value: ghost-user
        - name: database__connection__password
          value: "password"
        - name: database__connection__host
          value: mysql-service 
        - name: url 
          value: http://146.148.86.138:80
        ports:
        - containerPort: 2368
  
