#Installation and configuration of ghost deployment 
#following https://ghost.org/docs/ghost-cli/
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  namespace: ascn-cluster
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:5.14.1
        env: 
        - name: database__connection__database 
          value: ghost
        - name: database__connection__user
          value: "userexample"
        - name: database__connection__password
          value: "passwordexample"
        - name: database__connection__host
          value: mysql-service 
        - name: url 
          value: http://34.72.52.90:80
        - name: mail__transport
          value: SMTP
        - name: mail__options__service
          value: Mailgun
        - name: mail__options__host
          value: "smtp.mailtrap.io"
        - name: mail__options__port
          value: "465"
        - name: mail__options__secure
          value: "false"
        - name: mail__options__auth__user
          value: "eeeaa0e6c2f6b2"
        - name: mail__options__auth__pass
          value: "4fed9c0f437876"
        ports:
        - containerPort: 2368
  
