---

- name: Create storage class
  kubernetes.core.k8s:
      state: present
      src: kubernets/mysql-create_pvc.yml
      wait: true

- name: Claim pvc 
  kubernetes.core.k8s:
    state: present
    src: kubernets/mysql-pvc.yaml
  register: claim
  until: "claim.result.status.phase!='pending'"
  retries: 10
  delay: 2

- name: Get mysql secret credentials
  shell: "gcloud secrets versions access latest --secret=mysql"
  register: result

- name: Processar secret
  ansible.builtin.set_fact:
    sql_user: "{{result.stdout_lines[0]}}"
    sql_pass: "{{result.stdout_lines[1]}}"

- name: Update mysql-deployment
  template: src=templates/mysql-deployment.yaml dest=roles/ghost_db/kubernets/mysql-deployment.yaml


- name: Deploy MySQL
  kubernetes.core.k8s:
    state: present
    src: kubernets/mysql-deployment.yaml
    wait: true


- name: Expose MySQL service
  kubernetes.core.k8s:
    state: present
    src: kubernets/mysql-service.yaml
    wait: true