---

- name: Create storage class
  kubernetes.core.k8s:
      state: present
      src: kubernets/mysql-create_pvc.yml
      wait: true

- name: Claim pvc 
  kubernetes.core.k8s:
    state: present
    src: kubernets/mysql-pvc.yaml
  register: claim
  until: "claim.result.status.phase!='pending'"
  retries: 10
  delay: 2

- name: Deploy MySQL
  kubernetes.core.k8s:
    state: present
    src: kubernets/mysql-deployment.yaml
    wait: true


- name: Expose MySQL service
  kubernetes.core.k8s:
    state: present
    src: kubernets/mysql-service.yaml
    wait: true