---
# # Service for exposing MySQL
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-service # logical name of the service, which will also become the DNS name of the service when it is created.
#   namespace: ascn-cluster
#   labels:
#     app: mysql
#     tier: database
# spec:
#   type: ClusterIP # apenas disponivel dentro do cluster
#   selector:
#     app: mysql
#   ports:
#     - targetPort: 3306 # port that containers are listening on
#       port: 3306 # port number exposed internally in the cluster

# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: ascn-cluster
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: mysql
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the primary: mysql-0.mysql.
apiVersion: v1
kind: Service
metadata:
  name: mysql-read-service
  namespace: ascn-cluster
  labels:
    app: mysql
    readonly: "true"
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql
