---
# Service for exposing MySQL
apiVersion: v1
kind: Service
metadata:
  name: mysql-service # logical name of the service, which will also become the DNS name of the service when it is created.
  namespace: ascn-cluster
  labels:
    app: mysql
    tier: database
spec:
  type: ClusterIP # apenas disponivel dentro do cluster
  selector:
    app: mysql
  ports:
    - targetPort: 8000 # port that containers are listening on
      port: 8000 # port number exposed internally in the cluster