---
# Deployment for MySQL - ADAPTAR
apiVersion: v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: ascn-cluster
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 4
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env: # The variables below could be set on a ConfigMap object
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
            - name: MYSQL_DATABASE
              value: ghost
            - name: MYSQL_USER
              value: "userexample"
            - name: MYSQL_PASSWORD
              value: "passwordexample"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: standard
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
