#https://ghost.org/docs/ghost-cli/
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  namespace: ascn-cluster
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:5.14.1
        env: # The variables below could be set on a ConfigMap object
        - name: database__connection__database 
          value: ghost
        - name: database__connection__user
          value: "{{sql_user}}"
        - name: database__connection__password
          value: "{{sql_pass}}"
        - name: database__connection__host
          value: mysql-service 
        - name: url 
          value: {{ ghost_url }}
        - name: mail__transport
          value: SMTP
        - name: mail__options__service
          value: Mailgun
        - name: mail__options__host
          value: "{{mail_host}}"
        - name: mail__options__port
          value: "{{mail_port}}"
        - name: mail__options__secure
          value: "{{mail_secure|lower}}"
        - name: mail__options__auth__user
          value: "{{mail_user}}"
        - name: mail__options__auth__pass
          value: "{{mail_pass}}"
        ports:
        - containerPort: 2368
  

