#https://ghost.org/docs/ghost-cli/
---

- name: Update mysql-deployment mysql credentials
  template: src=templates/ghost-deployment.yml dest=roles/ghost_app/deploy-ghost/kubernets/ghost-deployment.yml


- name: Deploy Ghost
  kubernetes.core.k8s:
    state: present
    src: kubernets/ghost-deployment.yml
    wait: true

  

- name: Expose Ghost service
  kubernetes.core.k8s:
    state: present
    src: kubernets/ghost-service.yml
    wait: true



- name: Get MySQL Pod Name
  kubernetes.core.k8s_info:
    kind: Pod
    label_selectors:
      - app = mysql
    wait: true
  register: mysql_pod

- debug:
    var: "{{sql_user}}"

- name: Wait for users table to be created
  kubernetes.core.k8s_exec:
    namespace: ascn-cluster
    pod: "{{ mysql_pod.resources[0].metadata.name }}"
    container: mysql
    command: mysql --user=userexample --password=passwordexample --database=ghost -t --execute="select * from users"
  register: result
  until: "result.stdout != ''"
  retries: 10 #tabelas podem ainda estar a ser criadas 
  delay: 10


- name: Update/Create Admin in MySQL
  kubernetes.core.k8s_exec:
    namespace: ascn-cluster
    pod: "{{ mysql_pod.resources[0].metadata.name }}"
    container: mysql
    command: mysql --user={{sql_user}} --password={{sql_pass}} -t --database=ghost --execute="update users set name='ascn', password='$2b$10$0ruNjdRRsyAqrxpb5cGi7Oj4IOzW6MqKluXS8n0H7.DPmrJIHW2Au', email='ascn@example.com', status='active' where id=1;"
  register: result
  until: "result is not failed"
  retries: 10 #tabelas podem ainda estar a ser criadas 
  delay: 10


- name: Get Ghost Service
  kubernetes.core.k8s_info:
    kind: Service
    label_selectors:
      - app = ghost
  register: ghost_service
  until: "ghost_service.resources[0].status.loadBalancer.ingress is defined"
  retries: 10
  delay: 10


- name: Extract Ghost IP
  set_fact:
    new_ghost_ip: "{{ ghost_service.resources[0].status.loadBalancer.ingress[0].ip }}"

- name: Make new url
  set_fact:
    ghost_url: http://{{new_ghost_ip}}:{{ghost_port}}
    

- name: Update ghost_ip and ghost_url on inventory
  template: src=templates/gcp.yml dest=inventory/gcp.yml

- name: Update ghost-deployment
  template: src=templates/ghost-deployment.yml dest=roles/ghost_app/deploy-ghost/kubernets/ghost-deployment.yml


- name: Update Ghost
  kubernetes.core.k8s:
    state: present
    src: kubernets/ghost-deployment.yml
    wait: true

- name: Check Dashboards
  shell: 'gcloud monitoring dashboards list --filter="displayName=Ghost-Monitor"'
  register: result
  retries: 10
  delay: 10


- name: Create Dashboard
  shell: "gcloud monitoring dashboards create --config-from-file=templates/Ghost_Monitor.json"
  when: "result.stderr == 'Listed 0 items.'"
  retries: 10
  delay: 10





